# bashly completion                                        -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/bashly-framework/completely)
# Modifying it manually is not recommended

_bashly_completions_route_flag_expects_value() {
  case "$1:$2" in
    4:--env|4:-e) return 0 ;;
    4:--wrap|4:-r) return 0 ;;
    5:--source|5:-s) return 0 ;;
    8:--show|8:-s) return 0 ;;
  esac

  return 1
}

_bashly_completions_resolve_route() {
  route_id=
  route_word_count=-1
  route_has_positionals=0
  positional_index=0
  if (( ${#non_options[@]} >= 0 )) &&
    (( 0 > route_word_count ))
  then
    route_id=0
    route_word_count=0
    route_has_positionals=0
    positional_index=$((${#non_options[@]} - 0))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "init" || "${non_options[0]}" == "i" ]]
  then
    route_id=1
    route_word_count=1
    route_has_positionals=0
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "preview" || "${non_options[0]}" == "p" ]]
  then
    route_id=2
    route_word_count=1
    route_has_positionals=0
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "validate" || "${non_options[0]}" == "v" ]]
  then
    route_id=3
    route_word_count=1
    route_has_positionals=0
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "generate" || "${non_options[0]}" == "build" || "${non_options[0]}" == "g" ]]
  then
    route_id=4
    route_word_count=1
    route_has_positionals=0
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "add" || "${non_options[0]}" == "a" ]]
  then
    route_id=5
    route_word_count=1
    route_has_positionals=1
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "doc" ]]
  then
    route_id=6
    route_word_count=1
    route_has_positionals=1
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "completions" || "${non_options[0]}" == "c" ]]
  then
    route_id=7
    route_word_count=1
    route_has_positionals=0
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "render" ]]
  then
    route_id=8
    route_word_count=1
    route_has_positionals=1
    positional_index=$((${#non_options[@]} - 1))
  fi

  if (( ${#non_options[@]} >= 1 )) &&
    (( 1 > route_word_count )) &&
    [[ "${non_options[0]}" == "shell" || "${non_options[0]}" == "s" ]]
  then
    route_id=9
    route_word_count=1
    route_has_positionals=0
    positional_index=$((${#non_options[@]} - 1))
  fi

}

_bashly_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=
  if ((COMP_CWORD > 0)); then
    prev=${COMP_WORDS[$((COMP_CWORD - 1))]}
  fi

  local completed=()
  if ((COMP_CWORD > 1)); then
    completed=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi

  local non_options=()
  local completed_options=()
  local route_id=
  local route_word_count=-1
  local route_has_positionals=0
  local positional_index=0
  _bashly_completions_resolve_route

  local skip_next=0
  for word in "${completed[@]}"; do
    if ((skip_next)); then
      skip_next=0
      continue
    fi

    if [[ "${word:0:1}" == "-" ]]; then
      completed_options+=("$word")
      if _bashly_completions_route_flag_expects_value "$route_id" "$word"; then
        skip_next=1
      fi
      continue
    fi

    non_options+=("$word")
    _bashly_completions_resolve_route
  done

  COMPREPLY=()

  if [[ -z "$route_id" ]] || { (( route_word_count == 0 )) && (( !route_has_positionals )) && [[ "${cur:0:1}" != "-" ]]; }; then
    while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "init i preview p validate v generate build g add a doc completions c render shell s" -- "$cur")
    return
  fi

  case "$route_id:$prev" in
    4:--env|4:-e)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "development production" -- "$cur")
      return
      ;;
    4:--wrap|4:-r)
      return
      ;;
    5:--source|5:-s)
      return
      ;;
    8:--show|8:-s)
      return
      ;;
  esac

  if [[ "${cur:0:1}" == "-" ]]; then
    case "$route_id" in
      0)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --version|-v) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--version" "-v")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      1)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --minimal|-m) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--minimal" "-m")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      2)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      3)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --verbose|-v) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--verbose" "-v")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      4)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --env|-e) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--env" "-e")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --force|-f) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--force" "-f")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --quiet|-q) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--quiet" "-q")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --upgrade|-u) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--upgrade" "-u")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --watch|-w) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--watch" "-w")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --wrap|-r) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--wrap" "-r")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      5)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --force|-f) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--force" "-f")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --list|-l) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--list" "-l")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --source|-s) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--source" "-s")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      6)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --index|-i) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--index" "-i")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      7)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --install|-i) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--install" "-i")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --uninstall|-u) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--uninstall" "-u")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      8)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --watch|-w) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--watch" "-w")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --show|-s) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--show" "-s")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --list|-l) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--list" "-l")
        fi
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --about|-a) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--about" "-a")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
      9)
        local words=()
        local option_seen=0
        for completed_option in "${completed_options[@]}"; do
          case "$completed_option" in
            --help|-h) option_seen=1 ;;
          esac
        done
        if ((!option_seen)); then
          words+=("--help" "-h")
        fi
        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")
        return
        ;;
    esac
  fi

  case "$route_id:$positional_index" in
    5:0)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "colors completions completions_script completions_yaml config help hooks ini lib render_markdown render_markdown_github render_mandoc settings stacktrace strings validations yaml" -- "$cur")
      return
      ;;
    6:0)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "arg arg.allowed arg.completions arg.default arg.help arg.name arg.repeatable arg.required arg.validate command command.alias command.args command.catch_all command.commands command.completions command.default command.dependencies command.environment_variables command.examples command.expose command.extensible command.filename command.filters command.flags command.footer command.function command.group command.help command.help_header_override command.name command.private command.variables command.version environment_variable environment_variable.default environment_variable.help environment_variable.name environment_variable.private environment_variable.required environment_variable.validate flag flag.alias flag.allowed flag.arg flag.completions flag.conflicts flag.default flag.help flag.long flag.needs flag.private flag.repeatable flag.required flag.short flag.unique flag.validate variable variable.name variable.value" -- "$cur")
      return
      ;;
    8:0)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W ":mandoc :markdown :markdown_github" -- "$cur")
      return
      ;;
  esac
} &&
  complete -F _bashly_completions bashly

# ex: filetype=sh
